In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#회귀
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error

In [1]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

In [2]:
iris = load_iris()
logreg = LogisticRegression(max_iter=1000)

In [5]:
scores = cross_val_score(logreg, iris.data, iris.target)
scores.mean(), scores
# score라고 회귀에 다 되는 거 아님~

(0.9733333333333334,
 array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ]))

In [6]:
scores = cross_val_score(logreg, iris.data, iris.target, cv=10)
# cv값 안 주면 5겹, 저렇게 10겹 주면 10겹 
# p. 344
print("교차검증점수:", scores)

교차검증점수: [1.         0.93333333 1.         1.         0.93333333 0.93333333
 0.93333333 1.         1.         1.        ]


모델이 트레이닝 데이터에 민감한 경우

언더피팅 : 가장 난이도 낮음
오버피팅 : 모델을 조정하면 어떻게 솟아날 구멍이 보임
k-교차검증
어느 정도 선까지는 언더피팅을 해도 터지지 않는 선까지 학습이 가능
장점 
1. 평균적 스코어값 알 수 있음 : 왜냐면 이 모델에서는 보통 한 세트씩 빼고 계산하는 게 일반적으로 일어나서 그럼
모델이 훈련데이터에 민감함 
데이터셋이 작을 때 좀 더 효과적으로 쓸 수 잇음.
2.

In [14]:
from sklearn.model_selection import cross_validate
res = cross_validate(logreg, iris.data, iris.target, return_train_score=True)
display(res)

{'fit_time': array([0.00997281, 0.01296377, 0.0090003 , 0.00999689, 0.00900078]),
 'score_time': array([0.00099707, 0.0009973 , 0.        , 0.        , 0.        ]),
 'test_score': array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ]),
 'train_score': array([0.96666667, 0.96666667, 0.98333333, 0.98333333, 0.975     ])}

In [13]:
res_df = pd.DataFrame
display(res_df)
print("평균 시간과 점수 : \n", res_df.mean())

pandas.core.frame.DataFrame

TypeError: mean() missing 1 required positional argument: 'self'

### 교차 검증 상세 옵션

In [17]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5)

In [21]:
kfold = KFold(n_splits=3)
print("교차 검증 점수:\n", cross_val_score(logreg, iris.data, iris.target, cv=kfold))

교차 검증 점수:
 [0. 0. 0.]


In [20]:
kfold = KFold(n_splits=3, shuffle=True, random_state=0)
print("교차 검증 점수:\n", cross_val_score(logreg, iris.data, iris.target, cv=kfold))

교차 검증 점수:
 [0.98 0.96 0.96]


In [22]:
from sklearn.model_selection import cross_validate
res=cross_validate(logreg, iris.data, iris.target, return_train_score=True)
display(res)

{'fit_time': array([0.00997233, 0.01399899, 0.00897574, 0.00997329, 0.00997233]),
 'score_time': array([0.00099897, 0.        , 0.00099754, 0.        , 0.        ]),
 'test_score': array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ]),
 'train_score': array([0.96666667, 0.96666667, 0.98333333, 0.98333333, 0.975     ])}

## 교차 검증의 장점
### ㅇㅇㅇ

In [ ]:
from sklearn.model_selection import KFold